### ISSUE TITLE
Background Image Issue

### ISSUE THREAD

**Issue by chxp82q** [tomocafe/wordwall#4]
When trying to use a background image, for example: 
`./wordwall --logo=manjaro --color='#8fbcbb' --bg-image='back.png' wallpaper.png`, the resulted image is just the logo with a black background. 

If I adjust the box parameter when pasting the image, `bg_image.paste(overlay, (50, 125) , overlay)`, I get the whole logo shifted over, with the background I wanted peeking. Here are the images:

[Result](https://imgur.com/zM6BZpU)
[Adjusted Box Parameter Result](https://imgur.com/DUkjDat)

It seems that when generated the logo with a background image, the color behind the logo isn't transparent.

**Comment by tomocafe** [comment]
This should be fixed now. Was messing around with this on the master branch. Should have switched to another branch... sorry about that!
